### ISSUE TITLE
Docker hubへのImageアップロード

### ISSUE THREAD

**Issue by Mizunanari** [coias/coias-docker-compose#3]
- [ ] docker hubアカウントの作成
- [x] リポジトリの譲渡
- [ ] Docker hubの設定
- [ ] 自動buildの設定

**Comment by Mizunanari** [comment]
mizunanariで仮アップロード

**Comment by urakawa-seitaro** [comment]
coiasdockerというdocker hubアカウント作りました。
coiasというリポジトリ を作成しました。
リポジトリ の譲渡はどのように行えば良いでしょう。不慣れで申し訳ないです。
譲渡を行えば、Docker hubの設定と自動buildの設定はお任せできるという理解で良いでしょうか？

**Comment by Mizunanari** [comment]
@urakawa-seitaro 
アカウントを作成していただき、ありがとうございます。
githubにつきましては、アカウントを指定していただければ、こちらで設定できると思います。
dodker hubにつきましてはimageのアップロードをこちらからさせていただければと。

[salck](https://coiashq.slack.com/archives/C034Z0GDEBX/p1648693550962119)でも投稿させていただきましたが、数人で管理を行うのであれば組織アカウントの方がよろしいかと思います。

自動buildに関しましては、努力目標とさせていただきたく思います。（やらない可能性が高いです。）
現状のimageはコンテナとして起動する際に最新のコードをダウンロードいたしますので、imageを一度アップロードしてしまえば更新作業はいらないと考えております。
